"""Backend interfaces and reference implementations."""

from tuc.backends.base import Backend, BackendCapability, LoweringResult
from tuc.backends.claim_review import (
    MANIFEST_CLAIM_LOAD_STATUSES,
    MANIFEST_CLAIM_REVIEW_CONTRACT,
    MANIFEST_CLAIM_REVIEW_REPORT_SCHEMA_VERSION,
    MANIFEST_CLAIM_REVIEW_STATUSES,
    MAX_MANIFEST_CLAIM_REVIEW_CASES,
    MAX_MANIFEST_CLAIM_REVIEW_FIELD_BYTES,
    MAX_MANIFEST_CLAIM_REVIEW_ISSUES,
    MAX_MANIFEST_CLAIM_REVIEW_REPORT_BYTES,
    ManifestClaimReviewCase,
    ManifestClaimReviewInput,
    ManifestClaimReviewIssue,
    ManifestClaimReviewReport,
    build_manifest_claim_review_report,
    dump_manifest_claim_review_report,
    manifest_claim_review_report_to_dict,
)
from tuc.backends.conformance import (
    CONFORMANCE_REPORT_SCHEMA_VERSION,
    MVP_CONFORMANCE_OPERATION_KINDS,
    BackendConformanceError,
    BackendConformanceIssue,
    BackendConformanceReport,
    assert_backend_conformance,
    build_conformance_graph,
    conformance_report_to_dict,
    dump_backend_conformance_report,
    run_backend_conformance,
)
from tuc.backends.registry import (
    BackendRegistration,
    BackendRegistry,
    BackendRegistryError,
    BackendSupportDiagnostic,
)
from tuc.backends.simulator import LinearAlgebraSimulatorBackend, SystolicArraySimulatorBackend

__all__ = [
    "Backend",
    "BackendCapability",
    "BackendConformanceError",
    "BackendConformanceIssue",
    "BackendConformanceReport",
    "BackendRegistration",
    "BackendRegistry",
    "BackendRegistryError",
    "BackendSupportDiagnostic",
    "CONFORMANCE_REPORT_SCHEMA_VERSION",
    "LinearAlgebraSimulatorBackend",
    "LoweringResult",
    "MANIFEST_CLAIM_LOAD_STATUSES",
    "MANIFEST_CLAIM_REVIEW_CONTRACT",
    "MANIFEST_CLAIM_REVIEW_REPORT_SCHEMA_VERSION",
    "MANIFEST_CLAIM_REVIEW_STATUSES",
    "MVP_CONFORMANCE_OPERATION_KINDS",
    "MAX_MANIFEST_CLAIM_REVIEW_CASES",
    "MAX_MANIFEST_CLAIM_REVIEW_FIELD_BYTES",
    "MAX_MANIFEST_CLAIM_REVIEW_ISSUES",
    "MAX_MANIFEST_CLAIM_REVIEW_REPORT_BYTES",
    "ManifestClaimReviewCase",
    "ManifestClaimReviewInput",
    "ManifestClaimReviewIssue",
    "ManifestClaimReviewReport",
    "SystolicArraySimulatorBackend",
    "assert_backend_conformance",
    "build_manifest_claim_review_report",
    "build_conformance_graph",
    "conformance_report_to_dict",
    "dump_backend_conformance_report",
    "dump_manifest_claim_review_report",
    "manifest_claim_review_report_to_dict",
    "run_backend_conformance",
]
